import type { Metadata } from "next";
import { Inter, Syne } from "next/font/google";
import "./globals.css";
import { cn } from "@/utils/classmerger";

const inter = Inter({ subsets: ["latin"] });
const syne = Syne({ subsets: ["latin", "greek", "latin-ext"] });

export const metadata: Metadata = {
  title: "Soul Scocity",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn('bg-slate-950', syne.className)} >{children}</body>
    </html>
  );
}
